spring:
  application:
    name: UserMicroservice
  datasource:
    url: jdbc:mysql://localhost:3306/qeatsschema 
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 8080
